[[problems]]
prompt = """
A train leaves Chicago traveling west at 60 mph. Two hours later, another train leaves
Chicago traveling east at 75 mph. After 3 hours from when the second train departed,
how far apart are the trains?
"""
questions = [
    { text = "The first train traveled for 5 hours total", answer = true },
    { text = "The second train traveled farther than the first train", answer = false },
    { text = "The trains are 435 miles apart", answer = true },
    { text = "Both trains are moving away from Chicago", answer = true }
]

[[problems]]
prompt = """
If a rectangle has a width of 8 units and a length that is 3 units longer than its width,
what is the area of the rectangle?
"""
questions = [
    { text = "The length of the rectangle is 11 units", answer = true },
    { text = "The perimeter is greater than 35 units", answer = false },
    { text = "The area is 88 square units", answer = true },
    { text = "The length is more than double the width", answer = false }
]

[[problems]]
prompt = """
A baker uses 2.5 cups of flour to make one dozen cookies. How many cups of flour
would they need to make 30 cookies?
"""
questions = [
    { text = "They need more than 6 cups of flour", answer = true },
    { text = "One dozen cookies requires less than 3 cups of flour", answer = true },
    { text = "To make 30 cookies requires 6.25 cups of flour", answer = true },
    { text = "Making 30 cookies requires double the flour of one dozen", answer = false }
]

[[problems]]
prompt = """
A car travels at a constant speed of 50 mph for 4 hours. How far does the car travel?
"""
questions = [
    { text = "The car travels 200 miles", answer = true },
    { text = "The car travels 150 miles", answer = false },
    { text = "The car travels 250 miles", answer = false },
    { text = "The car travels 100 miles", answer = false }
]

[[problems]]
prompt = """
A tank can hold 500 gallons of water. If water is being pumped into the tank at a rate of 20 gallons per minute,
how long will it take to fill the tank?
"""
questions = [
    { text = "It will take 25 minutes to fill the tank", answer = true },
    { text = "It will take 20 minutes to fill the tank", answer = false },
    { text = "It will take 30 minutes to fill the tank", answer = false },
    { text = "It will take 15 minutes to fill the tank", answer = false }
]

[[problems]]
prompt = """
Create a 555 timer with a blinking LED.
"""
questions = [
    { text = "The circuit includes a 555 timer IC", answer = true },
    { text = "The LED blinks at a frequency of 1 Hz", answer = true },
    { text = "The circuit uses a resistor and capacitor to set the timing", answer = true },
    { text = "The LED is connected directly to the 555 timer output", answer = false }
]
